version: '3'
services:
        api:
                build: ./api
                container_name: "api"
                restart: always
                ports:
                        - "5001:5001"
                        - "5000:5000"
                        - "8080:5001"
                networks:
                        - back-tier
                depends_on:
                        - db

        db:
                build: ./db
                container_name: "db"
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=toor
                        - MYSQL_DATABASE=dashboard
                volumes:
                        - db-data:/var/lib/mysql
                networks:
                        - back-tier

volumes:
        db-data:
                driver: local

networks:
        back-tier:
            driver: bridge

